### ISSUE TITLE
Bad CPU type in executable 

### ISSUE THREAD

**Issue by mxwllcarmack** [bluewavenet/fadecandyserver#9]
Tried to run the fcserver-osc and got this bad CPU type in executable error. Any ideas?

**Comment by bluewavenet** [comment]
@mxwllcarmack 

> fcserver-osc 

Eh?

> bad CPU type in executable 

Can you describe what it is you have tried at least with a little bit of detail...

Probably the wrong target architecture.

You have to cross compile using the OpenWrt SDK. The example ipk is for mips_24kc SoC.

**Comment by mxwllcarmack** [comment]
Yes the built binary in the bin folder for OSX. It causes that error.If i try to build the program with make submodules, I get different errors, “not a git repo” and missing a .json file.Are there any install instructions? I didn’t see anything related to OpenWrt SDK.Really appreciate the help.Thanks-mlcs e n t  v i a  m o b i l e 📡On Sep 23, 2024, at 5:59 AM, Rob White ***@***.***> wrote:﻿
@mxwllcarmack

fcserver-osc
Eh?


bad CPU type in executable

Can you describe what it is you have tried at least with a little bit of detail...
Probably the wrong target architecture.
You have to cross compile using the OpenWrt SDK. The example ipk is for mips_24kc SoC.

**Comment by bluewavenet** [comment]
@mxwllcarmack 
From the README.md:

> This repository is specifically to enable OpenWrt support

https://github.com/bluewavenet/fadecandyserver

This is the OpenWrt Fadecandy server, designed to be used on an OpenWrt device.
The installable ipk included in the release is for the mips_24kc architecture.
A good example is:
https://www.gl-inet.com/products/gl-ar300m/

For OpenWrt on other architectures you would use the OpenWrt SDK to cross compile.

**Comment by mxwllcarmack** [comment]
I'm trying to run the fcserver on my Mac, with original fadecandies. I'm not using OpenWrt. So this wouldn't be a good fit for me, then?

**Comment by bluewavenet** [comment]
@mxwllcarmack 

> I'm not using OpenWrt. So this wouldn't be a good fit for me, then?

As I pointed out previously:

> This repository is specifically to enable OpenWrt support

One of the purposes of this Fadecandy Server for OpenWrt is to enable many fadecandy/DMX devices to be controlled from a central location using wifi to connect to multiple OpenWrt controllers.

**Comment by mxwllcarmack** [comment]
Got it. Regardless of the OpenWrt support, this is the best living repo of fadecandy, and I can't run the precompiled version of the server OR compile it from scratch due to outdated packages and broken dependencies. So for anyone who has a legacy fade candy setup, that's a problem. If there's any ideas to fix that from you or anyone else, it would be a welcome update to these files. I'm trying to run it on MacOSX Monterey. I will also try running/building fcserver on windows using the files here and report back.

**Comment by mxwllcarmack** [comment]
So far my investigations have found: 

The main issues encountered while building the Fadecandy Server on macOS involve architecture compatibility and missing dependencies. The build process attempts to compile for the deprecated i386 architecture, which is no longer supported in recent macOS versions, leading to numerous warnings and errors related to missing required architectures in system libraries. Additionally, there are issues with deprecated functions and macros, such as kIOMasterPortDefault, which have been replaced in newer macOS SDKs.

**Comment by bluewavenet** [comment]
@mxwllcarmack 
Yes it is very old. The last time i looked at this was 5 years ago.
The original author, Micah Elizabeth Scott, seems to have taken a huff and deleted her Github account...

You can find the original where she moved it to:
https://git.approximate.life/fadecandy

I hope this helps.
